//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppWithAsync
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_TBL
    {
        public int STD_ID { get; set; }
        public string STD_NAME { get; set; }
        public string STD_FATHER_NAME { get; set; }
        public string STD_CLASS { get; set; }
        public Nullable<int> STD_MOBILENUMBER { get; set; }
        public string STD_CITY { get; set; }
    }
}
